Public Class InfoRecordReq
    Public VENDOR As String = ""
    Public MATNR As String = ""
    Public PURORG As String = ""
    Public WERKS As String = ""
    Public STANDARD As String = ""
    Public SUBCONT As String = ""
    Public PIPEZ As String = ""
    Public CON As String = ""
    Public REM1 As String = ""
    Public REM2 As String = ""
    Public REM3 As String = ""
    Public VEN_MAT As String = ""
    Public COUNTRY As String = ""
    Public REGION As String = ""
    Public VEN_MAT_GRP As String = ""
    Public MANUF As String = ""
    Public SALES_PER As String = ""
    Public TELEPH As String = ""
    Public ORD_UNIT As String = ""
    Public ORD_DIN As String = ""
    Public ORD_NUM As String = ""
    Public NUMBERZ As String = ""
    Public PLAN_DEL_TIME As String = ""
    Public PUR_GRP As String = ""
    Public STND_QTY As String = ""
    Public MIN_QTY As String = ""
    Public ROUND_PROF As String = ""
    Public CONF_KEY As String = ""
    Public TAX_CODE As String = ""
    Public NET_PRICE As String = ""
    Public WAERS As String = ""
    Public VALID_ON As String = ""
    Public VALID_TO As String = ""
    Public COND As String = ""
    Public PRICE As String = ""
End Class

Public Class InfoRecordRes
    Public Property VENDOR As String = ""
    Public Property MATNR As String = ""
    Public Property INFNR As String = ""
    Public Property CONFIRM As String = ""
    Public Property MESSAGE As String = ""
End Class