Public Class MaterialMasterReq
    Public MATERIAL As String = ""
    Public IND_SECTOR As String = ""
    Public MATL_TYPE As String = ""
    Public BASIC_VIEW As String = ""
    Public SALES_VIEW As String = ""
    Public PURCHASE_VIEW As String = ""
    Public MRP_VIEW As String = ""
    Public STORAGE_VIEW As String = ""
    Public ACCOUNT_VIEW As String = ""
    Public COST_VIEW As String = ""
    Public MATL_DESC As String = ""
    Public LANGU As String = ""
    Public MATL_GROUP As String = ""
    Public BASE_UOM As String = ""
    Public DIVISION As String = ""
    Public PLANT As String = ""
    Public TRANS_GRP As String = ""
    Public LOADINGGRP As String = ""
    Public AVAILCHECK As String = ""
    Public PROFIT_CTR As String = ""
    Public PUR_GROUP As String = ""
    Public MANU_MAT As String = ""
    Public MRP_TYPE As String = ""
    Public MRP_CTRLER As String = ""
    Public LOTSIZEKEY As String = ""
    Public REORDER_PT As String = ""
    Public ROUND_VAL As String = ""
    Public MAX_STOCK As String = ""
    Public PLND_DELRY As String = ""
    Public PROC_TYPE As String = ""
    Public SAFETY_STK As String = ""
    Public BACKFLUSH As String = ""
    Public ISS_ST_LOC As String = ""
    Public SLOC_EXPRC As String = ""
    Public PERIOD_IND As String = ""
    Public PLANT_D As String = ""
    Public STGE_LOC As String = ""
    Public VAL_AREA As String = ""
    Public PRICE_CTRL As String = ""
    Public VAL_CLASS As String = ""
    Public MOVING_PR As String = ""
    Public ORIG_MAT As String = ""
    Public MFR_PRTNUMB As String = ""
End Class


Public Class MaterialMasterRes
    Public Property MANU_MAT As String = ""
    Public Property MATERIAL As String = ""
    Public Property CONFIRM As String = ""
    Public Property MESSAGE As String = ""
End Class