Public Class clsJSONArray
    Public Property Supplier_Code As String
    Public Property Supplier_Name As String
    Public Property Address As String
    Public Property Phone As String
    Public Property Fax As String
    Public Property Country As String
    Public Property President_Director As String
    Public Property President_Director_Email As String
    Public Property Vice_President_Director As String
    Public Property Vice_President_Director_Email As String
    Public Property Marketing_Director As String
    Public Property Marketing_Director_Email As String
    Public Property Marketing_General_Manager As String
    Public Property Marketing_General_Manager_Email As String
    Public Property Marketing_Manager As String
    Public Property Marketing_Manager_Email As String
    Public Property Plant_Director As String
    Public Property Plant_Director_Email As String
    Public Property Plant_Manager As String
    Public Property Plant_Manager_Email As String
    Public Property Marketing_Sales As String
    Public Property Marketing_Sales_Email As String
    Public Property Email As String
    Public Property Period_Code As String
    Public Property SupplierType As String
    Public Property Certification As String
    Public Property QualityAudit_Score As String
    Public Property DeliveryAudit_Score As String
    Public Property EHS_Value As String
    Public Property PPM As String
    Public Property Mother_Company As String
    Public Property Product_Name As String
    Public Property OEM_Customer As String
End Class
